### PR TITLE
Final

### PR DESCRIPTION
**Pull request by phfdonda**
### Hello!
This is the final version of the Apple clone page. I have added a markdown.md page to serve as a small tour of the structure of the site, and also a link for the preview of the website - please note that it will only be possible to visualize the Live Preview after the merge since the Live Preview accesses the master branch and not the final branch.
Thank you for your review, and have a fantastic day!

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Pedro!  
### Your project looks :+1: amazing!
Just a few corrections are required:
* [ ] Images are displaying only when you open it with live server. You need to correct path to your images, so that it can be easily displayed in any browser. Right now it looks like this:
image
* [ ] Link to live version in `README` file is displaying empty document. You can use [this website](http://raw.githack.com/) to create live version link without any complications.  

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by phfdonda** [comment]
I've completed the changes that were requested! 
Please review once more!

**Review by pelzolga123 — APPROVED** [review]
Approved!

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
